[project]
name = "ASCII_IMAGE_PY"
version = "0.1.4"
description = "Bitmap to ASCII Image Generator using Python"
readme = "README.md"
authors = [
    { name = "Manu11-Pro" }
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/Manu11-Pro/ASCII_IMAGE"

[tool.setuptools]
package-dir = {"" = "src"}

[project.scripts]
convert_to_ascii = "ascii_image.main:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
